name: CI

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  run-tests:
    name: 'Run tests'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven

      - name: Run check style
        uses: nikitasavinov/checkstyle-action@0.6.0
        continue-on-error: true
        with:
          checkstyle_version: 10.17.0
          checkstyle_config: 'config/checkstyle/mod_v10.17.0_google_checks.xml'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: 'github-pr-check'
          tool_name: 'Checkstyle'

      - name: Run tests
        run: mvn test
        env:
          ACCESS_OPTIONS: |-
            baseURL=${{ secrets.BASE_URL }};
            userEmail=${{ secrets.USER_EMAIL }};
            userPassword=${{ secrets.USER_PASSWORD }}
          BROWSER_OPTIONS: |-
            browserType=chromium;
            viewportWidth=1920;
            viewportHeight=1080;
            headlessMode=true;
            slowMoMode=0;
            tracingMode=true;
            videoMode=true
          CI_RUN: true

      - name: Attach artefacts on failure
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: Artefacts
          path: target/artefact/
          retention-days: 1

      - name: Get Allure history
        uses: actions/checkout@v4.2.2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build Allure report with history
        uses: simple-elf/allure-report-action@v1.12
        if: always()
        with:
          allure_results: './target/allure-results'

      - name: Deploy Allure report to GitHub pages
        uses: peaceiris/actions-gh-pages@v4.0.0
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
